import { NextRequest,NextResponse } from 'next/server';
import { getMemoryDb } from '@/lib/db';
import { requireOwner,ownerGateConfigured } from '@/lib/trading/auth';

export const runtime='nodejs'; export const dynamic='force-dynamic';
const TARGET={archive:'nli',parishId:'1032',registerId:'000631963',catalogueId:'vtls000631963',coverage:{from:1782,to:1809},seedPage:55,
  parishUrl:'https://registers.nli.ie/parishes/1032',registerUrl:'https://registers.nli.ie/registers/vtls000631963',seedUrl:'https://registers.nli.ie/pages/vtls000631963_055',catalogueUrl:'https://catalogue.nli.ie/Record/vtls000631963'} as const;
async function gate(){if(!ownerGateConfigured())return null;const result=await requireOwner();return result.ok?null:NextResponse.json({ok:false,error:result.reason},{status:result.status});}
async function schema(){const sql=getMemoryDb();
  await sql`CREATE TABLE IF NOT EXISTS genealogy_crawl_jobs (id BIGSERIAL PRIMARY KEY,frontier_id TEXT,archive TEXT NOT NULL,source_url TEXT NOT NULL,register_id TEXT,page_hint INTEGER,status TEXT NOT NULL DEFAULT 'proposed',objective TEXT NOT NULL,target_names TEXT[] NOT NULL DEFAULT '{}',year_from INTEGER,year_to INTEGER,pages_discovered INTEGER NOT NULL DEFAULT 0,pages_downloaded INTEGER NOT NULL DEFAULT 0,pages_scanned INTEGER NOT NULL DEFAULT 0,last_error TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(source_url,frontier_id))`;
  await sql`CREATE TABLE IF NOT EXISTS genealogy_pages (id BIGSERIAL PRIMARY KEY,job_id BIGINT NOT NULL REFERENCES genealogy_crawl_jobs(id) ON DELETE CASCADE,page_number INTEGER,source_url TEXT NOT NULL,original_path TEXT,sha256 TEXT,width INTEGER,height INTEGER,status TEXT NOT NULL DEFAULT 'discovered',metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(job_id,source_url))`;
  await sql`CREATE TABLE IF NOT EXISTS genealogy_crawl_checkpoints (id BIGSERIAL PRIMARY KEY,job_id BIGINT NOT NULL REFERENCES genealogy_crawl_jobs(id) ON DELETE CASCADE,phase TEXT NOT NULL,cursor TEXT,status TEXT NOT NULL,detail JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(job_id,phase,cursor))`;
  return sql;
}
export async function GET(){const denied=await gate();if(denied)return denied;try{const sql=await schema();const rows=await sql`SELECT j.*,d.id decision_id,d.mission FROM genealogy_crawl_jobs j LEFT JOIN genealogy_research_decisions d ON d.selected_frontier_id=j.frontier_id AND d.superseded_at IS NULL WHERE j.frontier_id='power-richard-1787' ORDER BY j.id DESC LIMIT 1`;const checkpoints=rows[0]?await sql`SELECT * FROM genealogy_crawl_checkpoints WHERE job_id=${rows[0].id} ORDER BY created_at`:[];return NextResponse.json({ok:true,target:TARGET,job:rows[0]??null,checkpoints});}catch(error:unknown){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}}
export async function POST(){const denied=await gate();if(denied)return denied;try{const sql=await schema();const decisions=await sql`SELECT * FROM genealogy_research_decisions WHERE superseded_at IS NULL ORDER BY id DESC LIMIT 1`;const decision=decisions[0];if(!decision)return NextResponse.json({ok:false,error:'CORE must select a research mission first'},{status:409});if(decision.selected_frontier_id!=='power-richard-1787')return NextResponse.json({ok:false,error:'No archive adapter is resolved for the selected frontier yet'},{status:409});
  const mission=decision.mission;const metadata={adapter:'nli-browser-session-v1',decision_id:decision.id,parish_id:TARGET.parishId,parish_url:TARGET.parishUrl,register_url:TARGET.registerUrl,catalogue_url:TARGET.catalogueUrl,register_coverage:TARGET.coverage,seed_page:TARGET.seedPage,acquisition_policy:{public_viewer_only:true,min_delay_seconds:1.5,max_pages_per_run:25,resumable:true}};
  const jobs=await sql`INSERT INTO genealogy_crawl_jobs(frontier_id,archive,source_url,register_id,page_hint,status,objective,target_names,year_from,year_to,metadata)
    VALUES ('power-richard-1787','nli',${TARGET.seedUrl},${TARGET.registerId},${TARGET.seedPage},'queued',${String(mission.objective)},${mission.variants??['Power','Powers','Poer']},${mission.yearFrom??1782},${mission.yearTo??1792},${JSON.stringify(metadata)}::jsonb)
    ON CONFLICT(source_url,frontier_id) DO UPDATE SET status='queued',objective=EXCLUDED.objective,target_names=EXCLUDED.target_names,year_from=EXCLUDED.year_from,year_to=EXCLUDED.year_to,metadata=genealogy_crawl_jobs.metadata||EXCLUDED.metadata,last_error=NULL,updated_at=NOW() RETURNING *`;
  const job=jobs[0];await sql`INSERT INTO genealogy_pages(job_id,page_number,source_url,status,metadata) VALUES (${job.id},${TARGET.seedPage},${TARGET.seedUrl},'discovered',${JSON.stringify({role:'operator_seed',year_hint:null})}::jsonb) ON CONFLICT(job_id,source_url) DO NOTHING`;
  await sql`INSERT INTO genealogy_crawl_checkpoints(job_id,phase,cursor,status,detail) VALUES (${job.id},'resolve_register',${TARGET.catalogueId},'complete',${JSON.stringify({parish:'Thomastown, Ossory',coverage:TARGET.coverage,catalogue_url:TARGET.catalogueUrl})}::jsonb) ON CONFLICT(job_id,phase,cursor) DO UPDATE SET status='complete',detail=EXCLUDED.detail`;
  await sql`INSERT INTO genealogy_crawl_checkpoints(job_id,phase,cursor,status,detail) VALUES (${job.id},'browser_manifest','start','queued',${JSON.stringify({worker:'workers/nli_browser_harvest.mjs'})}::jsonb) ON CONFLICT(job_id,phase,cursor) DO UPDATE SET status='queued',detail=EXCLUDED.detail`;
  await sql`UPDATE genealogy_research_decisions SET status='executing' WHERE id=${decision.id}`;
  return NextResponse.json({ok:true,job,target:TARGET,workerPayload:{url:TARGET.seedUrl,mode:'discover',job_id:String(job.id),register_id:TARGET.registerId,checkpoint_api:'/api/genealogy/research/execute'}},{status:201});
}catch(error:unknown){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}}

export async function PATCH(request:NextRequest){const denied=await gate();if(denied)return denied;try{const body=await request.json();const jobId=Number(body.jobId);if(!jobId)return NextResponse.json({ok:false,error:'jobId is required'},{status:400});const allowed=new Set(['queued','running','complete','operator_required','retryable_error']);const checkpointStatus=String(body.status??'retryable_error');if(!allowed.has(checkpointStatus))return NextResponse.json({ok:false,error:'invalid checkpoint status'},{status:400});const sql=await schema();const phase=String(body.phase??'browser_manifest'),cursor=String(body.cursor??'start'),detail=body.detail??{};
  await sql`INSERT INTO genealogy_crawl_checkpoints(job_id,phase,cursor,status,detail) VALUES (${jobId},${phase},${cursor},${checkpointStatus},${JSON.stringify(detail)}::jsonb) ON CONFLICT(job_id,phase,cursor) DO UPDATE SET status=EXCLUDED.status,detail=EXCLUDED.detail,created_at=NOW()`;
  const jobStatus=checkpointStatus==='complete'?'manifest_ready':checkpointStatus==='operator_required'?'awaiting_browser':checkpointStatus==='running'?'running':checkpointStatus==='queued'?'queued':'retryable_error';const error=checkpointStatus==='retryable_error'||checkpointStatus==='operator_required'?String(detail.error??'browser acquisition paused'):null;
  const rows=await sql`UPDATE genealogy_crawl_jobs SET status=${jobStatus},last_error=${error},pages_discovered=GREATEST(pages_discovered,${Number(detail.pages_discovered??0)}),updated_at=NOW() WHERE id=${jobId} RETURNING *`;return NextResponse.json({ok:true,job:rows[0],checkpoint:{phase,cursor,status:checkpointStatus}});
}catch(error:unknown){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}}
